### ISSUE TITLE
Add ability to send individual email report

### ISSUE THREAD

**Issue by nharper** [nharper/allegro#29]
This report should show all tap in and tap out times, list presences/absences, and total missed count.

**Comment by davesw** [comment]
this report would be available to any SC, Kevin, or Glenn.  There would be a way to run this for an individual (I suggest keyed on chorus number).
Note if there are multiple tap times we should use the earliest time and latest time as check in and check out and only show those on the report.
[example of individual report.xlsx](https://github.com/nharper/allegro/files/1644900/example.of.individual.report.xlsx)

**Comment by nharper** [comment]
How much does this need to be an email report instead of another view, e.g. clicking on a Performer's name in the concerts attendance grid takes you to a page like in that example?

**Comment by davesw** [comment]
If it is a headache we can do the UI but I'd really like the attendance
report to be e-mailed.

I'll give you a call tomorrow.  Keep in mind I have to step up and do some
of the work. I'm feeling better and can do that now.

All my best
Dave
ᐧ

**Comment by nharper** [comment]
Fixed in 4cc3b81e289a49c1ae71b73b586b79e02ec8f700.
